import { GeneratedSchema, ExtractedRecord } from '@/types';

export function exportToCSV(records: ExtractedRecord[], schema: GeneratedSchema): string {
  const headers = ['id', ...schema.attributes.map(a => a.name), 'validationScore', 'isDuplicate', 'sources'];
  
  const rows = records.map(r => {
    const values = [
      r.id,
      ...schema.attributes.map(a => {
        const val = r.data[a.name];
        if (val === undefined || val === null) return '""';
        return `"${String(val).replace(/"/g, '""')}"`;
      }),
      r.validationScore,
      r.isDuplicate ? 'YES' : 'NO',
      `"${r.mergedSources.join(', ')}"`
    ];
    return values.join(',');
  });

  return [headers.join(','), ...rows].join('\n');
}

export function exportToJSON(records: ExtractedRecord[], schema: GeneratedSchema): string {
  return JSON.stringify({
    schema,
    exportedAt: new Date().toISOString(),
    totalRecords: records.length,
    records: records.map(r => ({
      id: r.id,
      data: r.data,
      validationScore: r.validationScore,
      isDuplicate: r.isDuplicate,
      provenance: r.provenance,
      mergedSources: r.mergedSources
    }))
  }, null, 2);
}

export function exportToMarkdownTable(records: ExtractedRecord[], schema: GeneratedSchema): string {
  const headers = ['#', ...schema.attributes.map(a => a.name), 'Status', 'Confidence'];
  const separator = headers.map(() => '---');

  const rows = records.map((r, i) => {
    const cols = [
      String(i + 1),
      ...schema.attributes.map(a => String(r.data[a.name] ?? '-').replace(/\|/g, '\\|')),
      r.isDuplicate ? '⚠️ Duplicate' : '✅ Verified',
      `${r.validationScore}%`
    ];
    return `| ${cols.join(' | ')} |`;
  });

  return [
    `# ${schema.entityName} Dataset`,
    `Generated by Provenance Data Intelligence Platform on ${new Date().toLocaleDateString()}`,
    '',
    `| ${headers.join(' | ')} |`,
    `| ${separator.join(' | ')} |`,
    ...rows
  ].join('\n');
}

export function exportToTSV(records: ExtractedRecord[], schema: GeneratedSchema): string {
  const headers = ['id', ...schema.attributes.map(a => a.name), 'validationScore', 'isDuplicate'];
  
  const rows = records.map(r => {
    const values = [
      r.id,
      ...schema.attributes.map(a => String(r.data[a.name] ?? '').replace(/\t/g, ' ')),
      r.validationScore,
      r.isDuplicate ? 'TRUE' : 'FALSE'
    ];
    return values.join('\t');
  });

  return [headers.join('\t'), ...rows].join('\n');
}

// ----------------------------------------------------
// Interactive Sandbox Export: Pandas Python Snippet
// ----------------------------------------------------
export function exportToPandasPython(records: ExtractedRecord[], schema: GeneratedSchema): string {
  const cleanData = records.map(r => r.data);
  return `# =======================================================
# Provenance — Interactive Pandas Sandbox
# Entity: ${schema.entityName} (${records.length} records)
# Generated: ${new Date().toISOString()}
# =======================================================

import pandas as pd
import json

raw_dataset = ${JSON.stringify(cleanData, null, 2)}

# Load into Pandas DataFrame
df = pd.DataFrame(raw_dataset)

# Display summary statistics and schema info
print(f"Loaded {len(df)} verified records conforming to ${schema.entityName} schema.")
print(df.info())
print("\nFirst 5 Records:")
print(df.head())

# Optional: Export directly to Parquet or SQLite
# df.to_parquet("${schema.entityName.toLowerCase()}_verified.parquet")
`;
}

// ----------------------------------------------------
// Interactive Sandbox Export: SQLite DDL & Insert Script
// ----------------------------------------------------
export function exportToSQLiteSQL(records: ExtractedRecord[], schema: GeneratedSchema): string {
  const tableName = schema.entityName.replace(/[^a-zA-Z0-9_]/g, '').toLowerCase() || 'records';
  
  const typeMap: Record<string, string> = {
    string: 'TEXT',
    number: 'REAL',
    currency: 'TEXT',
    url: 'TEXT',
    date: 'TEXT',
    badge: 'TEXT'
  };

  const colDefs = schema.attributes.map(attr => {
    const colName = attr.name.replace(/[^a-zA-Z0-9_]/g, '_');
    const colType = typeMap[attr.type] || 'TEXT';
    return `    ${colName} ${colType}${attr.required ? ' NOT NULL' : ''}`;
  });

  const columnsList = ['record_id', ...schema.attributes.map(a => a.name.replace(/[^a-zA-Z0-9_]/g, '_')), 'validation_score', 'is_duplicate'].join(', ');

  const insertStatements = records.map(r => {
    const vals = [
      `'${r.id}'`,
      ...schema.attributes.map(a => {
        const v = r.data[a.name];
        if (v === undefined || v === null) return 'NULL';
        return `'${String(v).replace(/'/g, "''")}'`;
      }),
      r.validationScore,
      r.isDuplicate ? 1 : 0
    ];
    return `INSERT INTO ${tableName} (${columnsList}) VALUES (${vals.join(', ')});`;
  });

  return `-- =======================================================
-- Provenance — SQLite DDL & Insert Script
-- Table: ${tableName} (${records.length} rows)
-- =======================================================

DROP TABLE IF EXISTS ${tableName};

CREATE TABLE ${tableName} (
    record_id TEXT PRIMARY KEY,
${colDefs.join(',\n')},
    validation_score INTEGER,
    is_duplicate INTEGER
);

-- Verified Entity Inserts:
${insertStatements.join('\n')}

SELECT COUNT(*) AS total_verified_rows FROM ${tableName};
`;
}
