import { GeneratedSchema, ExtractedRecord } from '@/types';

export function exportToCSV(records: ExtractedRecord[], schema: GeneratedSchema): string {
  const headers = ['id', ...schema.attributes.map(a => a.name), 'validationScore', 'isDuplicate', 'sources'];
  
  const rows = records.map(r => {
    const values = [
      r.id,
      ...schema.attributes.map(a => {
        const val = r.data[a.name];
        if (val === undefined || val === null) return '""';
        return `"${String(val).replace(/"/g, '""')}"`;
      }),
      r.validationScore,
      r.isDuplicate ? 'YES' : 'NO',
      `"${r.mergedSources.join(', ')}"`
    ];
    return values.join(',');
  });

  return [headers.join(','), ...rows].join('\n');
}

export function exportToJSON(records: ExtractedRecord[], schema: GeneratedSchema): string {
  return JSON.stringify({
    schema,
    exportedAt: new Date().toISOString(),
    totalRecords: records.length,
    records: records.map(r => ({
      id: r.id,
      data: r.data,
      validationScore: r.validationScore,
      isDuplicate: r.isDuplicate,
      provenance: r.provenance,
      mergedSources: r.mergedSources
    }))
  }, null, 2);
}

export function exportToMarkdownTable(records: ExtractedRecord[], schema: GeneratedSchema): string {
  const headers = ['#', ...schema.attributes.map(a => a.name), 'Status', 'Confidence'];
  const separator = headers.map(() => '---');

  const rows = records.map((r, i) => {
    const cols = [
      String(i + 1),
      ...schema.attributes.map(a => String(r.data[a.name] ?? '-').replace(/\|/g, '\\|')),
      r.isDuplicate ? '⚠️ Duplicate' : '✅ Verified',
      `${r.validationScore}%`
    ];
    return `| ${cols.join(' | ')} |`;
  });

  return [
    `# ${schema.entityName} Dataset`,
    `Generated by SynapseData Intelligence Platform on ${new Date().toLocaleDateString()}`,
    '',
    `| ${headers.join(' | ')} |`,
    `| ${separator.join(' | ')} |`,
    ...rows
  ].join('\n');
}

export function exportToTSV(records: ExtractedRecord[], schema: GeneratedSchema): string {
  const headers = ['id', ...schema.attributes.map(a => a.name), 'validationScore', 'isDuplicate'];
  
  const rows = records.map(r => {
    const values = [
      r.id,
      ...schema.attributes.map(a => String(r.data[a.name] ?? '').replace(/\t/g, ' ')),
      r.validationScore,
      r.isDuplicate ? 'TRUE' : 'FALSE'
    ];
    return values.join('\t');
  });

  return [headers.join('\t'), ...rows].join('\n');
}
